export const WEATHER_DATA_ALL = {
  units: 'e',
  narrative: 'Abundant sunshine. Near record high temperatures. High 94F. Winds NW at 5 to 10 mph.',
  temperature: 103,
  iconCode: 32,
  wxPhraseLong: 'Mostly Sunny',
  temperatureFeelsLike: 100,
  windDirectionCardinal: 'ESE',
  windSpeed: 166,
  precipChance: 100,
  precipType: 'rain',
  relativeHumidity: 100,
  uvIndex: 8,
  visibility: 7,
  pressureMeanSeaLevel: 1033,
  pressureTendencyCode: 1,
  sunriseTimeLocal: '5:00 am',
  sunsetTimeLocal: '8:00 pm',
  moonriseTimeLocal: '5:00 am',
  moonsetTimeLocal: '8:00 pm',
};

export const WEATHER_DATA_RAIN = {
  units: 'e',
  narrative: 'Abundant sunshine. Near record high temperatures. High 94F. Winds NW at 5 to 10 mph.',
  temperature: 103,
  iconCode: 32,
  wxPhraseLong: 'Mostly Sunny',
  temperatureFeelsLike: 100,
  windDirectionCardinal: 'ESE',
  windSpeed: 166,
  precipChance: 100,
  precipType: 'rain',
  relativeHumidity: 100,
  uvIndex: 8,
  sunriseTimeLocal: '5:00 am',
  sunsetTimeLocal: '8:00 pm',
};

export const WEATHER_DATA_SNOW = {
  units: 'e',
  narrative: 'Abundant sunshine. Near record high temperatures. High 94F. Winds NW at 5 to 10 mph.',
  temperature: -32,
  iconCode: 32,
  wxPhraseLong: 'Mostly Sunny',
  temperatureFeelsLike: 100,
  windDirectionCardinal: 'ESE',
  windSpeed: 166,
  precipChance: 100,
  precipType: 'snow',
  relativeHumidity: 100,
  uvIndex: 8,
  sunriseTimeLocal: '5:00 am',
  sunsetTimeLocal: '8:00 pm',
};

export const WEATHER_DATA_WINTRYMIX = {
  units: 'e',
  narrative: 'Abundant sunshine. Near record high temperatures. High 94F. Winds NW at 5 to 10 mph.',
  temperature: -32,
  iconCode: 32,
  wxPhraseLong: 'Mostly Sunny',
  temperatureFeelsLike: 100,
  windDirectionCardinal: 'ESE',
  windSpeed: 166,
  precipChance: 100,
  precipType: 'precip',
  relativeHumidity: 100,
  uvIndex: 8,
  sunriseTimeLocal: '5:00 am',
  sunsetTimeLocal: '8:00 pm',
};

export const WEATHER_DATA_DAY = {
  units: 'e',
  daypartName: 'Today',
  narrative: 'Abundant sunshine. Near record high temperatures. High 94F. Winds NW at 5 to 10 mph.',
  temperature: 103,
  iconCode: 32,
  wxPhraseLong: 'Mostly Sunny',
  temperatureFeelsLike: 100,
  windDirectionCardinal: 'ESE',
  windSpeed: 166,
  precipChance: 100,
  precipType: 'rain',
  relativeHumidity: 100,
  uvIndex: 8,
  sunriseTimeLocal: '5:00 am',
  sunsetTimeLocal: '8:00 pm',
};

export const WEATHER_DATA_NIGHT = {
  units: 'e',
  daypartName: 'Tonight',
  narrative: 'Abundant sunshine. Near record high temperatures. High 94F. Winds NW at 5 to 10 mph.',
  temperature: -32,
  iconCode: 27,
  wxPhraseLong: 'Mostly Sunny',
  temperatureFeelsLike: 100,
  windDirectionCardinal: 'ESE',
  windSpeed: 166,
  precipChance: 100,
  precipType: 'rain',
  relativeHumidity: 100,
  uvIndex: 8,
  moonriseTimeLocal: '10:00 pm',
  moonsetTimeLocal: '9:00 am',
};

export const WEATHER_DATA_HOURLY = {
  units: 'e',
  temperatureFeelsLike: 100,
  windDirectionCardinal: 'ESE',
  windSpeed: 166,
  relativeHumidity: 100,
  uvIndex: 8,
  wxPhraseLong: 'Light Rain',
};
